name = "swl-auth"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
GITHUB_CLIENT_ID = "Ov23liQXlfvtNS7h0inM"
# GITHUB_CLIENT_SECRET goes in secrets (wrangler secret put GITHUB_CLIENT_SECRET)
